### PR TITLE
Remove HTTP dependency

### PR DESCRIPTION
**Pull request by fanfilmu**
Proposed solution for https://github.com/pythonicrubyist/creek/issues/80

### CODE REVIEW

**Comment by mdavidn** [comment]
To avoid a breaking change to the API, you could use [OpenURI](https://apidock.com/ruby/OpenURI) rather than the `http` gem.

**Comment by fanfilmu** [comment]
Hi and thank you for your comment @mdavidn !

Sure, it is an option. Depends on what @pythonicrubyist decides, but in my opinion, we should not avoid the breaking change here... For me, it seems really weird for Excel parser library to be able to download files from the internet.

I would suggest going with the Unix philosophy here, do one thing and do it well ;)

**Comment by mdavidn** [comment]
I don't disagree. I just don't want a major version bump to be a reason to keep the `http` dependency.

**Comment by fordfischer** [comment]
I really appreciate the ease of parsing excel files from a remote location this allows. If it is removed maybe it could be a plugin, like [shrine](https://github.com/shrinerb/shrine) does.

**Comment by mdavidn** [comment]
Ruby already makes it _very_ easy to read files from a remote location. This library does not need additional dependencies to support that feature.

```rb
require 'open-uri'
URI('https://path/to/excel/file.xlsx').read
```

**Comment by pythonicrubyist** [comment]
I completely agree that this library should not have had the remote option at the first place, but I do not want to introduce a breaking change to a library with over over a milliton downloads.

**Pull request closed without merging**
