### PR TITLE
Added mapping cell ids with header column name

### PR DESCRIPTION
**Pull request by dimaaleks**
**What?**

Added possibility to map cells with header column name.

To be able to have smth like 
```
 {"OVERRIDE_ID"=>123,
  "Renewal_Month"=>"April",
  "OVERRIDE_YNFLAG"=>"N",
  "CLIENT_ID"=>123,
  "CLIENT_NAME"=>"OOYALA INC",
  "SET_ID"=>123,
  "DESCRIPTION"=>"20-21 GLExcess 19-20 WC"}
```
instead of
```
 {"A"=>123,
  "B"=>"April",
  "C"=>"N",
  "D"=>123,
  "E"=>"OOYALA INC",
  "F"=>123,
  "G"=>"20-21 GLExcess 19-20 WC"}
```

### CODE REVIEW

**Comment by dimaaleks** [comment]
@pythonicrubyist hey man! hope you have a great day! Can you pls take a look and say how can we proceed with these changes?

**Comment by pythonicrubyist** [comment]
@dimaaleks thanks for your contribution. The code looks good. Can you please add a unit test for this new feature? Once the unit test is added, I will merge the PR and release a new gem version. Thanks.

**Comment by dimaaleks** [comment]
@pythonicrubyist tests were added, pls check.
Thanks in advance!

**Comment by dimaaleks** [comment]
@pythonicrubyist hey man! sorry for being annoying but could you pls send some feedback :)

**Comment by dimaaleks** [comment]
@pythonicrubyist hey man! still need your review, thanks in advance!

**Pull request merged**
